In [1]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize
import re
import numpy as np
import pandas as pd

In [2]:
import string
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()
remove_stop= nltk.corpus.stopwords.words('english')
from nltk.stem import WordNetLemmatizer
from gensim.parsing.preprocessing import remove_stopwords

In [3]:
UK = """The United Kingdom is a state made up of the historic countries of England, Wales and Scotland, as well as Northern Ireland. It is known as the home of both modern parliamentary democracy and the Industrial Revolution. Two world wars and the end of empire diminished its role in the 20th century, and the 2016 referendum vote to leave the European Union has raised significant questions about the country's global role. Nonetheless, the United Kingdom remains an economic and military power with great political and cultural influence around the world.
His Majesty King Charles III ascended to the throne in September 2022, on the death of his mother Queen Elizabeth II. The UK's first British Asian prime minister, Mr Sunak took over from the previous prime minister, Liz Truss, just 49 days after she herself had taken over from Boris Johnson. Mr Truss was forced to resign after big tax cuts in a her mini-budget prompted financial turmoil. Mr Sunak became leader of the Conservative party without a ballot of its members when his only remaining rival Penny Mordaunt withdrew."""

rishi_sunak = """Hours after he took charge as the UK Prime Minister, Rishi Sunak Tuesday spoke with US President Joe Biden, said the White House. During the congratulatory call made by Biden, the leaders agreed on the importance of working together to support Ukraine and hold Russia accountable for its aggression, address the challenges posed by China, and secure sustainable and affordable energy resources, it added. Meanwhile, soon after taking over as the British Prime Minister, Rishi Sunak made key Cabinet appointments and decided to keep the new Chancellor, Jeremy Hunt, in place for economic stability. He brought back Indian-origin Suella Braverman as Home Secretary while James Cleverly will remain Foreign Secretary despite not being a Sunak loyalist. The 42-year-old became UK’s first Indian-origin British Prime Minister after being invited by King Charles III to form a government. He said that he had been appointed in part to fix the mistakes made by his predecessor Liz Truss and warned the country might have to face difficult decisions to overcome a “profound economic crisis”."""

india = """Just a decade ago, Indian GDP was the eleventh largest in the world. Now, with 7 percent growth forecast for 2022, India's economy has overtaken the United Kingdom's in terms of size, making it the fifth biggest. That's according to the latest figures from the International Monetary Fund. India's growth is accompanied by a period of rapid inflation in the UK, creating a cost of living crisis and the risk of a recession which the Bank of England predicts could last into 2024. This situation, coupled with a turbulent political period and the continued hangover of Brexit, led to Indian output overtaking that of the UK in the final quarter of 2021, with the first of 2022 offering no change in the ranking. Looking ahead, the IMF forecasts this to become the new status quo, with India expected to leap further ahead of the UK up to 2027 - making India the fourth largest economy by that time, too, and leaving the UK behind in sixth."""

In [6]:
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
docs_dataset = pd.DataFrame([UK,rishi_sunak, india])
docs_dataset.columns = ['Documents']
docs_dataset

                                           Documents
0  The United Kingdom is a state made up of the h...
1  Hours after he took charge as the UK Prime Min...
2  Just a decade ago, Indian GDP was the eleventh...

In [5]:
def punctuation_removal(txt):
  notations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
  for words in txt:
    if words in notations:
      txt = txt.replace(words, "")
  return txt.lower()
docs_dataset['punct_remove'] = docs_dataset['Documents'].apply(lambda y:punctuation_removal(y))

docs_dataset['punct_remove'] = docs_dataset['punct_remove'].apply(lambda x: w_tokenizer.tokenize(x))

def stopwords_removal(token_data):
  text =token_data
  output=[]
  for i in text:
    ft=remove_stopwords(i)
    if ft == '':
      continue 
    else :
      output.append(ft)
  return output

docs_dataset['final_doc']=docs_dataset['punct_remove'].apply(lambda x:stopwords_removal(x))
docs_dataset=docs_dataset.drop(columns=['punct_remove'],axis=1)
docs_dataset

,Documents,final_doc
0,The United Kingdom is a state made up of the h...,"[united, kingdom, state, historic, countries, ..."
1,Hours after he took charge as the UK Prime Min...,"[hours, took, charge, uk, prime, minister, ris..."
2,"Just a decade ago, Indian GDP was the eleventh...","[decade, ago, indian, gdp, eleventh, largest, ..."

In [7]:
total_words=[]
for i in range(3):
  tokens=docs_dataset.iloc[i]["final_doc"]
  total_words.append(tokens)
print(total_words)

[['united', 'kingdom', 'state', 'historic', 'countries', 'england', 'wales', 'scotland', 'northern', 'ireland', 'known', 'home', 'modern', 'parliamentary', 'democracy', 'industrial', 'revolution', 'world', 'wars', 'end', 'empire', 'diminished', 'role', '20th', 'century', '2016', 'referendum', 'vote', 'leave', 'european', 'union', 'raised', 'significant', 'questions', 'countrys', 'global', 'role', 'nonetheless', 'united', 'kingdom', 'remains', 'economic', 'military', 'power', 'great', 'political', 'cultural', 'influence', 'world', 'majesty', 'king', 'charles', 'iii', 'ascended', 'throne', 'september', '2022', 'death', 'mother', 'queen', 'elizabeth', 'ii', 'uks', 'british', 'asian', 'prime', 'minister', 'mr', 'sunak', 'took', 'previous', 'prime', 'minister', 'liz', 'truss', '49', 'days', 'taken', 'boris', 'johnson', 'mr', 'truss', 'forced', 'resign', 'big', 'tax', 'cuts', 'minibudget', 'prompted', 'financial', 'turmoil', 'mr', 'sunak', 'leader', 'conservative', 'party', 'ballot', 'members', 'remaining', 'rival', 'penny', 'mordaunt', 'withdrew'], ['hours', 'took', 'charge', 'uk', 'prime', 'minister', 'rishi', 'sunak', 'tuesday', 'spoke', 'president', 'joe', 'biden', 'said', 'white', 'house', 'congratulatory', 'biden', 'leaders', 'agreed', 'importance', 'working', 'support', 'ukraine', 'hold', 'russia', 'accountable', 'aggression', 'address', 'challenges', 'posed', 'china', 'secure', 'sustainable', 'affordable', 'energy', 'resources', 'added', 'soon', 'taking', 'british', 'prime', 'minister', 'rishi', 'sunak', 'key', 'cabinet', 'appointments', 'decided', 'new', 'chancellor', 'jeremy', 'hunt', 'place', 'economic', 'stability', 'brought', 'indianorigin', 'suella', 'braverman', 'home', 'secretary', 'james', 'cleverly', 'remain', 'foreign', 'secretary', 'despite', 'sunak', 'loyalist', '42yearold', 'uk’s', 'indianorigin', 'british', 'prime', 'minister', 'invited', 'king', 'charles', 'iii', 'form', 'government', 'said', 'appointed', 'fix', 'mistakes', 'predecessor', 'liz', 'truss', 'warned', 'country', 'face', 'difficult', 'decisions', 'overcome', '“profound', 'economic', 'crisis”'], ['decade', 'ago', 'indian', 'gdp', 'eleventh', 'largest', 'world', '7', 'percent', 'growth', 'forecast', '2022', 'indias', 'economy', 'overtaken', 'united', 'kingdoms', 'terms', 'size', 'making', 'fifth', 'biggest', 'thats', 'according', 'latest', 'figures', 'international', 'monetary', 'fund', 'indias', 'growth', 'accompanied', 'period', 'rapid', 'inflation', 'uk', 'creating', 'cost', 'living', 'crisis', 'risk', 'recession', 'bank', 'england', 'predicts', '2024', 'situation', 'coupled', 'turbulent', 'political', 'period', 'continued', 'hangover', 'brexit', 'led', 'indian', 'output', 'overtaking', 'uk', 'final', 'quarter', '2021', '2022', 'offering', 'change', 'ranking', 'looking', 'ahead', 'imf', 'forecasts', 'new', 'status', 'quo', 'india', 'expected', 'leap', 'ahead', 'uk', '2027', 'making', 'india', 'fourth', 'largest', 'economy', 'time', 'leaving', 'uk', 'sixth']]

In [8]:
#finding Unique words in all  the documents
def find_unique(tokens_list):
  n=len(tokens_list)
  s=1
  wordset=set(tokens_list[0])
  while s<n:
    uniq_wordset=wordset.union(set(tokens_list[s]))
    s=s+1
  return uniq_wordset


# set of unique words
unique_words=find_unique(total_words)
print(unique_words)

{'political', 'england', 'ii', 'brexit', 'johnson', 'great', 'size', 'remaining', 'democracy', 'monetary', '2022', 'bank', 'sunak', 'eleventh', 'empire', 'influence', 'time', 'turbulent', 'united', 'forced', 'quarter', 'cuts', 'overtaken', 'offering', 'new', 'power', 'financial', 'military', 'diminished', 'status', 'terms', 'according', 'thats', 'death', 'ranking', 'mother', 'ballot', 'quo', 'countrys', 'british', 'risk', 'overtaking', 'leave', 'accompanied', 'queen', 'nonetheless', 'biggest', 'leaving', 'minister', '49', 'kingdom', 'led', 'looking', 'penny', '7', 'end', 'gdp', 'september', 'leap', 'charles', 'elizabeth', 'truss', 'predicts', 'international', 'world', 'indias', 'minibudget', 'ahead', 'wales', 'scotland', 'economic', 'continued', 'party', 'previous', 'figures', 'industrial', '2016', 'liz', 'decade', 'throne', 'parliamentary', 'days', 'period', 'rapid', 'revolution', 'largest', 'ascended', 'mordaunt', 'referendum', 'tax', 'rival', 'fourth', 'final', 'latest', 'wars', 'vote', 'recession', 'mr', 'big', 'northern', 'questions', 'expected', 'output', 'taken', 'countries', 'sixth', 'european', 'known', 'king', 'crisis', 'indian', 'members', 'forecast', 'prompted', 'fifth', 'inflation', 'modern', 'asian', 'creating', '2027', 'took', 'prime', 'home', 'change', 'significant', 'majesty', 'cost', 'hangover', 'raised', 'remains', 'cultural', 'making', 'living', 'historic', 'coupled', 'leader', 'withdrew', 'ireland', '2021', 'india', 'uk', 'economy', 'percent', '20th', 'kingdoms', 'role', '2024', 'forecasts', 'conservative', 'global', 'fund', 'imf', 'resign', 'ago', 'situation', 'union', 'state', 'growth', 'iii', 'boris', 'century', 'turmoil', 'uks'}

In [9]:
def calculateBOW(wordset,doc):
  tf_diz = dict.fromkeys(wordset,0)
  for word in doc:
      tf_diz[word]=int(bool(doc.count(word)))

  return tf_diz

In [10]:
Bag_of_words=[]
for doc in total_words:
    Bag_of_words.append(calculateBOW(unique_words,doc))
Bag_of_words

[{'political': 1,
  'england': 1,
  'ii': 1,
  'brexit': 0,
  'johnson': 1,
  'great': 1,
  'size': 0,
  'remaining': 1,
  'democracy': 1,
  'monetary': 0,
  '2022': 1,
  'bank': 0,
  'sunak': 1,
  'eleventh': 0,
  'empire': 1,
  'influence': 1,
  'time': 0,
  'turbulent': 0,
  'united': 1,
  'forced': 1,
  'quarter': 0,
  'cuts': 1,
  'overtaken': 0,
  'offering': 0,
  'new': 0,
  'power': 1,
  'financial': 1,
  'military': 1,
  'diminished': 1,
  'status': 0,
  'terms': 0,
  'according': 0,
  'thats': 0,
  'death': 1,
  'ranking': 0,
  'mother': 1,
  'ballot': 1,
  'quo': 0,
  'countrys': 1,
  'british': 1,
  'risk': 0,
  'overtaking': 0,
  'leave': 1,
  'accompanied': 0,
  'queen': 1,
  'nonetheless': 1,
  'biggest': 0,
  'leaving': 0,
  'minister': 1,
  '49': 1,
  'kingdom': 1,
  'led': 0,
  'looking': 0,
  'penny': 1,
  '7': 0,
  'end': 1,
  'gdp': 0,
  'september': 1,
  'leap': 0,
  'charles': 1,
  'elizabeth': 1,
  'truss': 1,
  'predicts': 0,
  'international': 0,
  'world': 1,
  'indias': 0,
  'minibudget': 1,
  'ahead': 0,
  'wales': 1,
  'scotland': 1,
  'economic': 1,
  'continued': 0,
  'party': 1,
  'previous': 1,
  'figures': 0,
  'industrial': 1,
  '2016': 1,
  'liz': 1,
  'decade': 0,
  'throne': 1,
  'parliamentary': 1,
  'days': 1,
  'period': 0,
  'rapid': 0,
  'revolution': 1,
  'largest': 0,
  'ascended': 1,
  'mordaunt': 1,
  'referendum': 1,
  'tax': 1,
  'rival': 1,
  'fourth': 0,
  'final': 0,
  'latest': 0,
  'wars': 1,
  'vote': 1,
  'recession': 0,
  'mr': 1,
  'big': 1,
  'northern': 1,
  'questions': 1,
  'expected': 0,
  'output': 0,
  'taken': 1,
  'countries': 1,
  'sixth': 0,
  'european': 1,
  'known': 1,
  'king': 1,
  'crisis': 0,
  'indian': 0,
  'members': 1,
  'forecast': 0,
  'prompted': 1,
  'fifth': 0,
  'inflation': 0,
  'modern': 1,
  'asian': 1,
  'creating': 0,
  '2027': 0,
  'took': 1,
  'prime': 1,
  'home': 1,
  'change': 0,
  'significant': 1,
  'majesty': 1,
  'cost': 0,
  'hangover': 0,
  'raised': 1,
  'remains': 1,
  'cultural': 1,
  'making': 0,
  'living': 0,
  'historic': 1,
  'coupled': 0,
  'leader': 1,
  'withdrew': 1,
  'ireland': 1,
  '2021': 0,
  'india': 0,
  'uk': 0,
  'economy': 0,
  'percent': 0,
  '20th': 1,
  'kingdoms': 0,
  'role': 1,
  '2024': 0,
  'forecasts': 0,
  'conservative': 1,
  'global': 1,
  'fund': 0,
  'imf': 0,
  'resign': 1,
  'ago': 0,
  'situation': 0,
  'union': 1,
  'state': 1,
  'growth': 0,
  'iii': 1,
  'boris': 1,
  'century': 1,
  'turmoil': 1,
  'uks': 1},
 {'political': 0,
  'england': 0,
  'ii': 0,
  'brexit': 0,
  'johnson': 0,
  'great': 0,
  'size': 0,
  'remaining': 0,
  'democracy': 0,
  'monetary': 0,
  '2022': 0,
  'bank': 0,
  'sunak': 1,
  'eleventh': 0,
  'empire': 0,
  'influence': 0,
  'time': 0,
  'turbulent': 0,
  'united': 0,
  'forced': 0,
  'quarter': 0,
  'cuts': 0,
  'overtaken': 0,
  'offering': 0,
  'new': 1,
  'power': 0,
  'financial': 0,
  'military': 0,
  'diminished': 0,
  'status': 0,
  'terms': 0,
  'according': 0,
  'thats': 0,
  'death': 0,
  'ranking': 0,
  'mother': 0,
  'ballot': 0,
  'quo': 0,
  'countrys': 0,
  'british': 1,
  'risk': 0,
  'overtaking': 0,
  'leave': 0,
  'accompanied': 0,
  'queen': 0,
  'nonetheless': 0,
  'biggest': 0,
  'leaving': 0,
  'minister': 1,
  '49': 0,
  'kingdom': 0,
  'led': 0,
  'looking': 0,
  'penny': 0,
  '7': 0,
  'end': 0,
  'gdp': 0,
  'september': 0,
  'leap': 0,
  'charles': 1,
  'elizabeth': 0,
  'truss': 1,
  'predicts': 0,
  'international': 0,
  'world': 0,
  'indias': 0,
  'minibudget': 0,
  'ahead': 0,
  'wales': 0,
  'scotland': 0,
  'economic': 1,
  'continued': 0,
  'party': 0,
  'previous': 0,
  'figures': 0,
  'industrial': 0,
  '2016': 0,
  'liz': 1,
  'decade': 0,
  'throne': 0,
  'parliamentary': 0,
  'days': 0,
  'period': 0,
  'rapid': 0,
  'revolution': 0,
  'largest': 0,
  'ascended': 0,
  'mordaunt': 0,
  'referendum': 0,
  'tax': 0,
  'rival': 0,
  'fourth': 0,
  'final': 0,
  'latest': 0,
  'wars': 0,
  'vote': 0,
  'recession': 0,
  'mr': 0,
  'big': 0,
  'northern': 0,
  'questions': 0,
  'expected': 0,
  'output': 0,
  'taken': 0,
  'countries': 0,
  'sixth': 0,
  'european': 0,
  'known': 0,
  'king': 1,
  'crisis': 0,
  'indian': 0,
  'members': 0,
  'forecast': 0,
  'prompted': 0,
  'fifth': 0,
  'inflation': 0,
  'modern': 0,
  'asian': 0,
  'creating': 0,
  '2027': 0,
  'took': 1,
  'prime': 1,
  'home': 1,
  'change': 0,
  'significant': 0,
  'majesty': 0,
  'cost': 0,
  'hangover': 0,
  'raised': 0,
  'remains': 0,
  'cultural': 0,
  'making': 0,
  'living': 0,
  'historic': 0,
  'coupled': 0,
  'leader': 0,
  'withdrew': 0,
  'ireland': 0,
  '2021': 0,
  'india': 0,
  'uk': 1,
  'economy': 0,
  'percent': 0,
  '20th': 0,
  'kingdoms': 0,
  'role': 0,
  '2024': 0,
  'forecasts': 0,
  'conservative': 0,
  'global': 0,
  'fund': 0,
  'imf': 0,
  'resign': 0,
  'ago': 0,
  'situation': 0,
  'union': 0,
  'state': 0,
  'growth': 0,
  'iii': 1,
  'boris': 0,
  'century': 0,
  'turmoil': 0,
  'uks': 0,
  'hours': 1,
  'charge': 1,
  'rishi': 1,
  'tuesday': 1,
  'spoke': 1,
  'president': 1,
  'joe': 1,
  'biden': 1,
  'said': 1,
  'white': 1,
  'house': 1,
  'congratulatory': 1,
  'leaders': 1,
  'agreed': 1,
  'importance': 1,
  'working': 1,
  'support': 1,
  'ukraine': 1,
  'hold': 1,
  'russia': 1,
  'accountable': 1,
  'aggression': 1,
  'address': 1,
  'challenges': 1,
  'posed': 1,
  'china': 1,
  'secure': 1,
  'sustainable': 1,
  'affordable': 1,
  'energy': 1,
  'resources': 1,
  'added': 1,
  'soon': 1,
  'taking': 1,
  'key': 1,
  'cabinet': 1,
  'appointments': 1,
  'decided': 1,
  'chancellor': 1,
  'jeremy': 1,
  'hunt': 1,
  'place': 1,
  'stability': 1,
  'brought': 1,
  'indianorigin': 1,
  'suella': 1,
  'braverman': 1,
  'secretary': 1,
  'james': 1,
  'cleverly': 1,
  'remain': 1,
  'foreign': 1,
  'despite': 1,
  'loyalist': 1,
  '42yearold': 1,
  'uk’s': 1,
  'invited': 1,
  'form': 1,
  'government': 1,
  'appointed': 1,
  'fix': 1,
  'mistakes': 1,
  'predecessor': 1,
  'warned': 1,
  'country': 1,
  'face': 1,
  'difficult': 1,
  'decisions': 1,
  'overcome': 1,
  '“profound': 1,
  'crisis”': 1},
 {'political': 1,
  'england': 1,
  'ii': 0,
  'brexit': 1,
  'johnson': 0,
  'great': 0,
  'size': 1,
  'remaining': 0,
  'democracy': 0,
  'monetary': 1,
  '2022': 1,
  'bank': 1,
  'sunak': 0,
  'eleventh': 1,
  'empire': 0,
  'influence': 0,
  'time': 1,
  'turbulent': 1,
  'united': 1,
  'forced': 0,
  'quarter': 1,
  'cuts': 0,
  'overtaken': 1,
  'offering': 1,
  'new': 1,
  'power': 0,
  'financial': 0,
  'military': 0,
  'diminished': 0,
  'status': 1,
  'terms': 1,
  'according': 1,
  'thats': 1,
  'death': 0,
  'ranking': 1,
  'mother': 0,
  'ballot': 0,
  'quo': 1,
  'countrys': 0,
  'british': 0,
  'risk': 1,
  'overtaking': 1,
  'leave': 0,
  'accompanied': 1,
  'queen': 0,
  'nonetheless': 0,
  'biggest': 1,
  'leaving': 1,
  'minister': 0,
  '49': 0,
  'kingdom': 0,
  'led': 1,
  'looking': 1,
  'penny': 0,
  '7': 1,
  'end': 0,
  'gdp': 1,
  'september': 0,
  'leap': 1,
  'charles': 0,
  'elizabeth': 0,
  'truss': 0,
  'predicts': 1,
  'international': 1,
  'world': 1,
  'indias': 1,
  'minibudget': 0,
  'ahead': 1,
  'wales': 0,
  'scotland': 0,
  'economic': 0,
  'continued': 1,
  'party': 0,
  'previous': 0,
  'figures': 1,
  'industrial': 0,
  '2016': 0,
  'liz': 0,
  'decade': 1,
  'throne': 0,
  'parliamentary': 0,
  'days': 0,
  'period': 1,
  'rapid': 1,
  'revolution': 0,
  'largest': 1,
  'ascended': 0,
  'mordaunt': 0,
  'referendum': 0,
  'tax': 0,
  'rival': 0,
  'fourth': 1,
  'final': 1,
  'latest': 1,
  'wars': 0,
  'vote': 0,
  'recession': 1,
  'mr': 0,
  'big': 0,
  'northern': 0,
  'questions': 0,
  'expected': 1,
  'output': 1,
  'taken': 0,
  'countries': 0,
  'sixth': 1,
  'european': 0,
  'known': 0,
  'king': 0,
  'crisis': 1,
  'indian': 1,
  'members': 0,
  'forecast': 1,
  'prompted': 0,
  'fifth': 1,
  'inflation': 1,
  'modern': 0,
  'asian': 0,
  'creating': 1,
  '2027': 1,
  'took': 0,
  'prime': 0,
  'home': 0,
  'change': 1,
  'significant': 0,
  'majesty': 0,
  'cost': 1,
  'hangover': 1,
  'raised': 0,
  'remains': 0,
  'cultural': 0,
  'making': 1,
  'living': 1,
  'historic': 0,
  'coupled': 1,
  'leader': 0,
  'withdrew': 0,
  'ireland': 0,
  '2021': 1,
  'india': 1,
  'uk': 1,
  'economy': 1,
  'percent': 1,
  '20th': 0,
  'kingdoms': 1,
  'role': 0,
  '2024': 1,
  'forecasts': 1,
  'conservative': 0,
  'global': 0,
  'fund': 1,
  'imf': 1,
  'resign': 0,
  'ago': 1,
  'situation': 1,
  'union': 0,
  'state': 0,
  'growth': 1,
  'iii': 0,
  'boris': 0,
  'century': 0,
  'turmoil': 0,
  'uks': 0}]

In [11]:
df_bow_all = pd.DataFrame(Bag_of_words)
df_bow_all = df_bow_all.fillna(0)
df_bow_all = df_bow_all.T.astype(int)
df_bow_all

           0  1  2
political  1  0  1
england    1  0  1
ii         1  0  0
brexit     0  0  1
johnson    1  0  0
...       .. .. ..
difficult  0  1  0
decisions  0  1  0
overcome   0  1  0
“profound  0  1  0
crisis”    0  1  0

[234 rows x 3 columns]

In [12]:
df_bow_all['words'] = df_bow_all.index
word_tab=df_bow_all.reset_index()
word_tab=word_tab.drop(columns=['index'],axis=1)
word_tab

     0  1  2      words
0    1  0  1  political
1    1  0  1    england
2    1  0  0         ii
3    0  0  1     brexit
4    1  0  0    johnson
..  .. .. ..        ...
229  0  1  0  difficult
230  0  1  0  decisions
231  0  1  0   overcome
232  0  1  0  “profound
233  0  1  0    crisis”

[234 rows x 4 columns]

In [16]:
query = input('Enter your query:')

def extract_(query):
  query = word_tokenize(query)
  connecting_words = []
  cnt = 1
  different_words = []
  final=[]
  for word in query:
      if word.lower() != "and" and word.lower() != "or" and word.lower() != "not":
          final.append((word_tab.loc[word_tab['words'] == word.lower()].values.tolist())[0][0:3])
      elif word == 'and':
          final.append('and')
      elif word == 'not':
        final.append('not')
      else:
        final.append('or')
  return final

output = extract_(query)
print(output)

Enter your query:recession and uk
[[0, 0, 1], 'and', [0, 1, 1]]